version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.3
    - 3.13.4
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: testcontainers
    versions:
    - 3.3.0
  - dependency-name: sendgrid
    versions:
    - 6.5.0
    - 6.6.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pyjwt
    versions:
    - 2.0.1
  - dependency-name: uvicorn
    versions:
    - 0.13.3
