  version: '3.4'
  services:
    database:
      image: postgres:11.2
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: "${LOCAL_DB_USERNAME}"
        POSTGRES_PASSWORD: "${LOCAL_DB_PASSWORD}"
      network_mode: "host"
    
    microauth:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - database
      env_file:
        - .env
      network_mode: "host"