  version: '3.4'
  services:
    database:
      image: postgres:11.2
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: "${LOCAL_DB_USERNAME}"
        POSTGRES_PASSWORD: "${LOCAL_DB_PASSWORD}"
    microauth:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - database